### ISSUE TITLE
Asking for permission to improve

### ISSUE THREAD

**Issue by Zada5** [mariopepe/KindleAdRemover#8]
First thing - Thanks for the product! Helped me a lot. 
Second thing - I want to add the ability to set your own home screen saver - but I really don't know how this operation system works. 
Can you tell me where you learned to work with this OS? 
I want to open a PR that not only removes the ads but also lets you set your own screen saver images. 
Thanks

**Comment by mariopepe** [comment]
Hey!!! to be completely honest this is a sort of hacky way around the problem, rather than a proper OS modification.
To set your own screensaver you would need root access into the device (i.e. edit the folder of the OS itself) and to achieve that you need an exploit. And this method is super far from it, and unfortunately i am very incapable of making one.

I remember there were some open source exploit to achieve root privileges on old version of Kindle Os, you could start by searching for those and studying how they work, the exisiting ones use known webkit vulnerabilities (the kindle browser is based on webkit, and the update cycle is fairly slow, so a vulnerability on webkit discovered and patched today, can still exist into kindle browser version in 4/5 months from now, so you don't need to use zero days!).

Having said that achieving file system read/write from a webkit vulnerability is super hard, I wish i knew how to do it in details, but unfortunately I cannot help :( 

if you manage let us know tho!!!
